# fly.toml file generated for ajaxbits on 2022-03-31T09:54:58-05:00

app = "ajaxbits"

# kill_signal = "SIGINT"
# kill_timeout = 5
# processes = []

[build]
  image = "xeblogchallenge2022-0.1.0:develop"

# [env]
#
# [experimental]
#   allowed_public_ports = []
#   auto_rollback = true

[[services]]
  # http_checks = []
  internal_port = 8080
  # processes = ["app"]
  protocol = "tcp"
  # script_checks = []

  # [services.concurrency]
  #   hard_limit = 25
  #   soft_limit = 20
  #   type = "connections"

  [[services.ports]]
    # force_https = true
    handlers = ["http"]
    port = 80

  # [[services.ports]]
  #   handlers = ["tls", "http"]
  #   port = 443

  # [[services.tcp_checks]]
  #   grace_period = "1s"
  #   interval = "15s"
  #   restart_limit = 0
  #   timeout = "2s"
